server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Добавьте это
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/categories/**
            - Path=/compilations/**
            - Path=/admin/**
            - Path=/events/**
            - Path=/users/**
            - Path=/comments/**
          filters:
            - StripPrefix=1  # Важно!

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**
            - Path=/stats/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG